---
- hosts: all
  become: yes
  vars_files:
  - env_variables
  tasks:
  - name: Disabling Swap on all nodes
    shell: swapoff -a
  
  - name: Adding required firewall ports but stop the service
    firewalld:
     port: "{{ item }}"
     state: disabled
     permanent: yes
     immediate: yes
    with_items: "{{ master_ports if ('master' in group_names) else worker_ports }}"
  
  - name: FirewallD stopped
    shell: "systemctl stop firewalld && systemctl disable firewalld"

  - name: Commenting Swap entries in /etc/fstab
    replace:
     path: /etc/fstab
     regexp: '(^/.*swap*)'
     replace: '# \1'

  - name: Add IPs to /etc/hosts on master and workers
    lineinfile:
      dest: /etc/hosts
      regexp: '.*{{ item }}$'
      line: "{{ hostvars[item].ansible_host }} {{item}}"
      state: present
    when: hostvars[item].ansible_host is defined
    with_items: "{{ groups.all }}"
  
  - name: Enabling kernel modules
    shell: "modprobe br_netfilter"
    
  - name: Enabling Bridge Firewall Rule
    shell: "echo '1' > /proc/sys/net/bridge/bridge-nf-call-iptables"
  
  - name: Creating a sysctl file
    file:
     path: /etc/sysctl.d/99-kubernetes-cri.conf
     state: touch

  - name: Adding sysctl configurations.
    blockinfile:
     path: /etc/sysctl.d/99-kubernetes-cri.conf
     block: |
      net.bridge.bridge-nf-call-iptables  = 1
      net.ipv4.ip_forward                 = 1
      net.bridge.bridge-nf-call-ip6tables = 1

  - name: Apply sysctl configs
    shell: "sysctl --system"
  
  - name: Adding Docker repo..
    shell: |
      yum install -y yum-utils
      yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
      yum-config-manager --enable docker-ce-nightly
  
  - name: Installing containerD and setting it up..
    shell: |
      yum install -y containerd.io
      containerd config default > /etc/containerd/config.toml
      sed -i '/\[plugins.\"io.containerd.grpc.v1.cri\".containerd.runtimes.runc.options\]/a\\t\    SystemdCgroup = true' /etc/containerd/config.toml
      systemctl start containerd && systemctl enable containerd
  
  - name: Creating a repository file for Kubernetes
    file:
     path: /etc/yum.repos.d/kubernetes.repo
     state: touch

  - name: Adding Kubernetes repo file..
    blockinfile:
     path: /etc/yum.repos.d/kubernetes.repo
     block: |
      [kubernetes]
      name=Kubernetes
      baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-$basearch
      enabled=1
      gpgcheck=1
      repo_gpgcheck=1
      gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg

  - name: Installing kubernetes components and setting them up..
    shell: |
      yum install -y kubelet-1.21.0-0 kubeadm-1.21.0-0 kubectl-1.21.0-0
      systemctl enable kubelet.service
